# Generated by Django 2.2.7 on 2022-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='poll_result',
        ),
        migrations.AddField(
            model_name='choice',
            name='poll_result',
            field=models.BooleanField(default=False),
        ),
    ]
