# Generated by Django 2.2.7 on 2022-08-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_vote_user_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_number',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='answer',
        ),
    ]
